name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Trophies
        uses: lowlighter/metrics@latest
        with:
          filename: trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}
          # বেসিক স্ট্যাটস অফ করে দিচ্ছি, যাতে শুধু ট্রফি দেখায়
          base: ""
          # ট্রফি প্লাগিন অন করছি
          plugin_trophies: yes
          # আপনার অপছন্দের ট্রফিগুলো ফিল্টার (বাদ) করছি
          plugin_trophies_ignored: followers, issues, pullrequest, reviews
          # সুন্দর একটি ডার্ক কার্ড ডিজাইন
          config_theme: dark
